"""
EventFlux — Event ingestion router.

POST /v1/events/bulk
  - Validates payload with Pydantic (BulkEventRequest)
  - Enforces MAX_BATCH_SIZE
  - Enqueues events via EventQueue (pipelined XADD + MAXLEN trim)
  - Returns 202 with request_id, queued count, and stream length
  - Sets X-Request-ID response header
"""
from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException, Request, Response, status

from shared.models import BulkEventRequest, EventBulkResponse
from shared.queue import EventQueue
from shared.settings import get_api

logger = logging.getLogger("eventflux.api.events")

router = APIRouter(tags=["events"])

_api_cfg = get_api()


@router.post(
    "/events/bulk",
    status_code=status.HTTP_202_ACCEPTED,
    response_model=EventBulkResponse,
    summary="Ingest a batch of telemetry events",
)
async def bulk_ingest(
    payload: BulkEventRequest,
    request: Request,
    response: Response,
) -> EventBulkResponse:
    """
    Accept a batch of telemetry events and push them onto the Redis Stream.

    **Limits**
    - Minimum 1 event (Pydantic schema).
    - Maximum `MAX_BATCH_SIZE` events (env var, default 5 000).

    **Tracing**
    - Reads `request_id` from the request body or uses the UUID auto-generated
      by the schema.  The same ID is echoed via `X-Request-ID` header.

    **Returns** the number of events enqueued and the current stream length.
    """
    if len(payload.events) > _api_cfg.max_batch_size:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail=(
                f"Batch too large: received {len(payload.events)}, "
                f"maximum allowed is {_api_cfg.max_batch_size}."
            ),
        )

    # Prefer request_id from payload over the one generated by middleware
    request_id = str(payload.request_id)
    response.headers["X-Request-ID"] = request_id

    queue = EventQueue(request.app.state.redis)
    message_ids = await queue.enqueue_batch(payload.events)
    queued = len(message_ids)

    # Best-effort: get stream length for response (non-critical)
    stream_len: int | None = None
    try:
        info = await queue.stream_info()
        stream_len = info.length
    except Exception:  # noqa: BLE001
        pass

    logger.info(
        "request_id=%s queued=%d stream_len=%s first_id=%s",
        request_id,
        queued,
        stream_len,
        message_ids[0] if message_ids else "N/A",
    )

    return EventBulkResponse(
        request_id=request_id,
        queued=queued,
        stream_len=stream_len,
    )
